import java.util.Arrays;
import java.util.HashMap;

public class Aoc2202 {
  public static void main(String[] args) {
        /*
        (1 for Rock, 2 for Paper, and 3 for Scissors)
        X for Rock, Y for Paper, and Z for Scissors.
        A for Rock, B for Paper, and C for Scissors
         */
    var map = new HashMap<Character, Integer>(){{
      put('A', 1);
      put('B', 2);
      put('C', 3);
      put('X', 1);
      put('Y', 2);
      put('Z', 3);
    }};

    int r = 0;

    for (String in : getInput()) {
      int opp = map.get(in.charAt(0));
      int you = map.get(in.charAt(2));
      r += you;
      if (opp == you) {
        r += 3;
      }
      else if (you == opp + 1 || you == opp - 2) {
        r += 6;
      }
    }

    System.out.println(r);
  }

  private static String[] getInput() {
    return ("C Y\n" +
      "B Y\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "A Z\n" +
      "A Z\n" +
      "A Y\n" +
      "A X\n" +
      "A Z\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "A Z\n" +
      "A Z\n" +
      "A Y\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "C X\n" +
      "B X\n" +
      "A Y\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "C X\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "C Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B Y\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "A Z\n" +
      "B Y\n" +
      "A X\n" +
      "A Y\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "B Y\n" +
      "C Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "C X\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "A Y\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "C Z\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "A X\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "A Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "C Z\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "B Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "C X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "B Y\n" +
      "A X\n" +
      "A Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "A X\n" +
      "B Y\n" +
      "A X\n" +
      "A X\n" +
      "C X\n" +
      "C Y\n" +
      "B Y\n" +
      "A Z\n" +
      "C X\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "C X\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "B Y\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "A Z\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C X\n" +
      "B X\n" +
      "C X\n" +
      "C Z\n" +
      "C Y\n" +
      "B Z\n" +
      "C Z\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "C X\n" +
      "B Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "A Z\n" +
      "C X\n" +
      "A Y\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B Y\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "C X\n" +
      "B Y\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "B Y\n" +
      "C X\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "A Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "A X\n" +
      "C Z\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "C X\n" +
      "B X\n" +
      "C X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "B Z\n" +
      "B Y\n" +
      "A Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "A X\n" +
      "B Z\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "B Y\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C Z\n" +
      "A Y\n" +
      "A X\n" +
      "C Y\n" +
      "A Z\n" +
      "C X\n" +
      "A Z\n" +
      "A Z\n" +
      "C X\n" +
      "A X\n" +
      "A Z\n" +
      "B Z\n" +
      "A Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B Y\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "C X\n" +
      "B X\n" +
      "A X\n" +
      "C X\n" +
      "B Y\n" +
      "B Y\n" +
      "A Z\n" +
      "C Z\n" +
      "C Z\n" +
      "A X\n" +
      "C Y\n" +
      "A Y\n" +
      "A Z\n" +
      "B Z\n" +
      "A Z\n" +
      "A X\n" +
      "A Y\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "A X\n" +
      "B Y\n" +
      "C X\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "A X\n" +
      "C X\n" +
      "B X\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Y\n" +
      "A Y\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C X\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C X\n" +
      "C X\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "B Y\n" +
      "A Y\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "A Z\n" +
      "C X\n" +
      "B Y\n" +
      "B Z\n" +
      "C Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B Y\n" +
      "B Z\n" +
      "B Y\n" +
      "B X\n" +
      "A Z\n" +
      "C X\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "C Z\n" +
      "B Z\n" +
      "B Z\n" +
      "C X\n" +
      "C Y\n" +
      "A Y\n" +
      "C Y\n" +
      "A Y\n" +
      "B X\n" +
      "B Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "C Z\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C X\n" +
      "B X\n" +
      "C Y\n" +
      "B Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B Y\n" +
      "B Z\n" +
      "B Y\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "C Z\n" +
      "A Z\n" +
      "B X\n" +
      "C Z\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "B Z\n" +
      "B Y\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A Y\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "B Y\n" +
      "A X\n" +
      "C Z\n" +
      "A X\n" +
      "B Y\n" +
      "B X\n" +
      "A Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "B Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A X\n" +
      "B Y\n" +
      "A X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "A Y\n" +
      "B Z\n" +
      "A X\n" +
      "C X\n" +
      "A Z\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "A Z\n" +
      "B Y\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Z\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "A Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "B Z\n" +
      "A Z\n" +
      "C X\n" +
      "B Z\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "C X\n" +
      "B Z\n" +
      "A Z\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "C X\n" +
      "B Z\n" +
      "B Y\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "C Z\n" +
      "C Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A Y\n" +
      "B X\n" +
      "A Y\n" +
      "B Z\n" +
      "A Z\n" +
      "C Z\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "A Z\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "C X\n" +
      "A Z\n" +
      "B Y\n" +
      "A X\n" +
      "B X\n" +
      "A Z\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A Y\n" +
      "C X\n" +
      "B X\n" +
      "C X\n" +
      "B Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "A Z\n" +
      "A Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "A X\n" +
      "A Y\n" +
      "B Z\n" +
      "B Y\n" +
      "B Y\n" +
      "C X\n" +
      "A Z\n" +
      "A Z\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "A Y\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B Y\n" +
      "A X\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "A X\n" +
      "C X\n" +
      "C X\n" +
      "C Y\n" +
      "B X\n" +
      "C X\n" +
      "A X\n" +
      "C Y\n" +
      "B Y\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "B Y\n" +
      "B Y\n" +
      "A Y\n" +
      "A X\n" +
      "C Y\n" +
      "A X\n" +
      "C X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B Y\n" +
      "A X\n" +
      "C X\n" +
      "C X\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "C X\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "C X\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "C X\n" +
      "A Y\n" +
      "B Z\n" +
      "B Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "C X\n" +
      "C Y\n" +
      "B Y\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "B Y\n" +
      "C Y\n" +
      "B X\n" +
      "C X\n" +
      "C X\n" +
      "A Z\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C X\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "B Y\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Z\n" +
      "C Y\n" +
      "A Z\n" +
      "A Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B Y\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "B Y\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "C X\n" +
      "A Z\n" +
      "C X\n" +
      "B Z\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "C Z\n" +
      "C X\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "A Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "A Z\n" +
      "A X\n" +
      "C Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "C X\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Y\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "C Z\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "A X\n" +
      "A Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C X\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "B Y\n" +
      "A Z\n" +
      "B X\n" +
      "B Y\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "B Y\n" +
      "C X\n" +
      "B X\n" +
      "C X\n" +
      "A X\n" +
      "C X\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B Y\n" +
      "A X\n" +
      "B Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A X\n" +
      "C X\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "C X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "B Z\n" +
      "B Z\n" +
      "A Y\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "C Z\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "C X\n" +
      "B Z\n" +
      "B Y\n" +
      "C Z\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "A Y\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "C X\n" +
      "A X\n" +
      "A Z\n" +
      "B Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "A Z\n" +
      "C X\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Y\n" +
      "A X\n" +
      "A X\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B Y\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "A Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "A Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "A X\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "C X\n" +
      "A Z\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C X\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "A Y\n" +
      "A X\n" +
      "B Z\n" +
      "A Y\n" +
      "A Z\n" +
      "B X\n" +
      "C X\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Y\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "B X\n" +
      "C X\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "A Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C X\n" +
      "A Z\n" +
      "C Z\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "A X\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "A X\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B Y\n" +
      "A X\n" +
      "B Z\n" +
      "A Z\n" +
      "A Z\n" +
      "A Z\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "B Y\n" +
      "A Y\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "B Y\n" +
      "B X\n" +
      "C X\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "C X\n" +
      "B X\n" +
      "A Y\n" +
      "C Z\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "A Z\n" +
      "A X\n" +
      "B X\n" +
      "A X\n" +
      "A X\n" +
      "C Y\n" +
      "A Y\n" +
      "A X\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B Y\n" +
      "C Z\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "A X\n" +
      "A Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Z\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B Y\n" +
      "A X\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "C X\n" +
      "A Z\n" +
      "A Z\n" +
      "B Y\n" +
      "A X\n" +
      "A X\n" +
      "B Z\n" +
      "A Z\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "C X\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "A X\n" +
      "B Y\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C X\n" +
      "B X\n" +
      "B Y\n" +
      "C X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "B Y\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C Z\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "B Y\n" +
      "B Y\n" +
      "B Z\n" +
      "C X\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "B Y\n" +
      "C X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "B Z\n" +
      "A Y\n" +
      "C Y\n" +
      "B X\n" +
      "C Z\n" +
      "A Z\n" +
      "B Y\n" +
      "A Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "A Z\n" +
      "B Z\n" +
      "A X\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "C X\n" +
      "A Z\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Z\n" +
      "B Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "B Y\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "C X\n" +
      "B Y\n" +
      "B Y\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "B Y\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "C X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "C Z\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "A X\n" +
      "C X\n" +
      "B X\n" +
      "B Y\n" +
      "A X\n" +
      "B Z\n" +
      "A Z\n" +
      "B Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "B Y\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A X\n" +
      "C Z\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A Y\n" +
      "B Z\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A Y\n" +
      "A X\n" +
      "B X\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "C X\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "C Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "B Y\n" +
      "B Z\n" +
      "B Y\n" +
      "B X\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "A Y\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "C X\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A Y\n" +
      "C Z\n" +
      "A Z\n" +
      "C X\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A X\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B Y\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "A Z\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B Y\n" +
      "B Y\n" +
      "B X\n" +
      "A X\n" +
      "A Y\n" +
      "B Y\n" +
      "B Y\n" +
      "C Y\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B Y\n" +
      "A X\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "B Y\n" +
      "B Y\n" +
      "B X\n" +
      "A Z\n" +
      "A Z\n" +
      "A Z\n" +
      "A Y\n" +
      "B Z\n" +
      "C X\n" +
      "B X\n" +
      "C Y\n" +
      "C Z\n" +
      "B Y\n" +
      "C Y\n" +
      "C X\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B Y\n" +
      "B Z\n" +
      "A Z\n" +
      "C X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "C X\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "C Z\n" +
      "A X\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "C X\n" +
      "A Z\n" +
      "C Y\n" +
      "A Z\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "C Z\n" +
      "B X\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "A Z\n" +
      "C Y\n" +
      "B Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "A Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "A Z\n" +
      "C X\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B Y\n" +
      "B X\n" +
      "B X\n" +
      "C X\n" +
      "B X\n" +
      "A X\n" +
      "C X\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "C X\n" +
      "A Y\n" +
      "C X\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C X\n" +
      "A Z\n" +
      "B X\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B Y\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "A Y\n" +
      "C X\n" +
      "B X\n" +
      "C Z\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "C X\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "A Y\n" +
      "B Z\n" +
      "B X\n" +
      "B Y\n" +
      "A Z\n" +
      "A Y\n" +
      "A X\n" +
      "B Y\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "A Z\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "B Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "B Y\n" +
      "A Y\n" +
      "B Z\n" +
      "B X\n" +
      "A X\n" +
      "A Y\n" +
      "C Y\n" +
      "C X\n" +
      "B X\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A X\n" +
      "C Z\n" +
      "C X\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "C X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "B Z\n" +
      "B Y\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "B Z\n" +
      "A Y\n" +
      "C Y\n" +
      "A X\n" +
      "C X\n" +
      "B X\n" +
      "B Y\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B Y\n" +
      "B Z\n" +
      "B Y\n" +
      "B Z\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "B Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Z\n" +
      "C Y\n" +
      "A Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "A Y\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Z\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "C Z\n" +
      "A Z\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B Y\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B Y\n" +
      "C Y\n" +
      "B Z\n" +
      "C X\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "B Y\n" +
      "B Y\n" +
      "B Z\n" +
      "A Z\n" +
      "B Z\n" +
      "C X\n" +
      "C X\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "A Z\n" +
      "A Y\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "A Y\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "C X\n" +
      "B X\n" +
      "B Y\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "C Y\n" +
      "B Y\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "C Y\n" +
      "C X\n" +
      "C X\n" +
      "C Y\n" +
      "B Y\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "B X\n" +
      "C X\n" +
      "B Z\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "C X\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C X\n" +
      "B Z\n" +
      "C Y\n" +
      "B Y\n" +
      "A Z\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "C X\n" +
      "C Z\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "A X\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "C Z\n" +
      "B X\n" +
      "C Z\n" +
      "C Y\n" +
      "C X\n" +
      "C Y\n" +
      "B Y\n" +
      "A X\n" +
      "B Z\n" +
      "A Z\n" +
      "C X\n" +
      "B X\n" +
      "C X\n" +
      "A Z\n" +
      "A Y\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "A Z\n" +
      "A Z\n" +
      "B Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "B Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "C X\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "C X\n" +
      "C Y\n" +
      "A Z\n" +
      "C X\n" +
      "A Z\n" +
      "C Y\n" +
      "A X\n" +
      "C Y\n" +
      "A X\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "C X\n" +
      "A X\n" +
      "B Y\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "B X\n" +
      "A X\n" +
      "A X\n" +
      "A X\n" +
      "A X\n" +
      "B Z\n" +
      "B Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C Z\n" +
      "C Y\n" +
      "A X\n" +
      "B Y\n" +
      "C X\n" +
      "A Z\n" +
      "B X\n" +
      "B Z\n" +
      "A X\n" +
      "A X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "C Y\n" +
      "C Y\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "A Y\n" +
      "C Y\n" +
      "A Z\n" +
      "A X\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "C Y\n" +
      "B X\n" +
      "C Y\n" +
      "C Y\n" +
      "C Y\n" +
      "C Z\n" +
      "B X\n" +
      "C Y\n" +
      "C X\n" +
      "B Z\n" +
      "A Z\n" +
      "C Y\n" +
      "A Z\n" +
      "B Z\n" +
      "A Z\n" +
      "B X\n" +
      "A X\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "A X\n" +
      "B Z\n" +
      "A X\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "C Y\n" +
      "B X\n" +
      "B Z\n" +
      "C Y\n" +
      "B Z\n" +
      "B Z\n" +
      "B X\n" +
      "B Z\n" +
      "B X\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "B Y\n" +
      "B X\n" +
      "B X\n" +
      "A Z\n" +
      "B X\n" +
      "C Y\n" +
      "B X\n" +
      "B X\n" +
      "B X\n" +
      "B Z\n" +
      "A Z\n" +
      "B Y\n" +
      "B X\n" +
      "B Z\n" +
      "C X\n" +
      "C Y\n" +
      "B X\n" +
      "B Y\n" +
      "C Y\n" +
      "B X\n" +
      "C X\n" +
      "B X\n" +
      "C X\n" +
      "B Z\n" +
      "A Y\n" +
      "A Z\n" +
      "B Z\n" +
      "B Z\n" +
      "A X\n" +
      "A Z\n" +
      "B Z\n" +
      "B X\n" +
      "A Z\n" +
      "B Z\n" +
      "C Y\n" +
      "C Z\n" +
      "C Y\n" +
      "A Z\n" +
      "C Z\n" +
      "A Z\n" +
      "C Z\n" +
      "C Y\n" +
      "A Z\n" +
      "A Y\n" +
      "C Y").split("\n");
  }
}
